sudo: false
language: node_js
node_js:
  - 6
  - 7
  - 8
before_script:
  - npm install -g codecov
script:
  - node_modules/.bin/istanbul cover node_modules/.bin/jasmine-node --captureExceptions spec/e2e
  - codecov
